version: "3"
services:
  eureka-server:
    image: upskill-eureka-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    env_file:
      - src/main/resources/.env