version: "3"
services:
  eureka-server:
    image: upskill-eureka-server:latest
    container_name: eureka-server-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    env_file:
      - .env