version: "3"
services:
  eureka-server:
    image: manuellarbi/eureka-server-image:base
    container_name: gtp-eureka-server-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
#    env_file:
#      - src/main/resources/.env